config/routes.rb
Rails.application.routes.draw do

   devise_for :customers,controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions',
    passwords: "public/passwords"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }

  namespace :admin do

    resources :customers, only: [:index, :show, :edit, :update]
    resources:restaurants,only:[:index,:new,:create,:show,:edit,:update,:destroy]
    resources:reviews,only:[:index,:edit,:update]
    resources :genres, only: [:index, :create, :edit, :update]

  end

  scope module: :public do
    root 'homes#top'
    get 'map_search' => 'homes#map_search', as: 'map_search'


    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'

    resources :customers, only: [:show] do
      member do
        get :favorites
        get :reviews
      end
    end


    resources :restaurants, only: [ :show, :index] do
      resource :favorites, only: [:create, :destroy]
      resources :reviews, only: [:create,:destroy,:update]
    end

  end





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_review, only: [:edit, :update]

  def index
    @reviews = Review.all
  end

  def edit
    #@customer = @review.customer
  end

  def update
    @review.update(review_params) ? (redirect_to admin_reviews_path, notice: 'レビュー情報の更新が完了しました。') : (render :edit)
  end

  private
  def review_params
    params.require(:review).permit(:comment,:rate,:customer_id,:restaurant_id,:is_active)
  end

  def ensure_review
    @review = Review.find(params[:id])
  end

end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/edit.html.erb
<section class="container">
	<h3>レビュー詳細・編集</h3>
	<div class="admin-page">
		<%= form_with(model:@review, url: admin_review_path(@review.id)) do |f| %>
		<table class="admin_review_info">
			<thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>評価</td>
					<td><div id="star-rate"></div></td>
					<script>
						$('#star-rate').empty();
						$('#star-rate').raty({
							size      : 36,
							starOff   : '<%= asset_path('star-off.png') %>',
							starOn    : '<%= asset_path('star-on.png') %>',
							half      : false,
							readOnly  : true,
							score: <%= @review.rate %>,
						});
					</script>
				</tr>
				<tr>
					<td>コメント</td>
					<td><%= f.text_field :comment %></td>
				</tr>
				<tr>
					<td><%= f.label :sales_status, "表示ステータス" %></td>
					<td class="select_field">
						<%= f.radio_button :is_active, true %>
						<%= f.label :is_active, "有効", value: true, class: "text-active" %>
						<%= f.radio_button :is_active, false %>
						<%= f.label :is_active, "無効", value: false, class: "text-invalid" %>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="flex align-center pl5">
			<%= f.submit "変更を保存", class: "admin-btn" %>
		</div>
		<% end %>
	</div>
</section>

app/views/admin/reviews/index.html.erb
<div class="container">
  <h3>レビュー一覧</h3>
  <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">投稿日時</th>
      <th scope="col">投稿者</th>
      <th scope="col">店名</th>
      <th scope="col">表示ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
    <tr>
      <td>
        <%= link_to edit_admin_review_path(review.id) do %>
         <%= review.created_at.strftime('%Y/%m/%d %H:%M') %>
        <% end %>
      </td>
      <td>
        <%= review.customer.name %>
      </td>
      <td>
        <%= review.restaurant.name %>
      </td>
      <td>
        <%= review.is_active %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>