config/routes.rb
Rails.application.routes.draw do

   devise_for :customers,controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions',
    passwords: "public/passwords"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }

  namespace :admin do

    resources :customers, only: [:index, :show, :edit, :update]
    resources:restaurants,only:[:index,:new,:create,:show,:edit,:update,:destroy]
    resources:reviews,only:[:index,:edit,:update]
    resources :genres, only: [:index, :create, :edit, :update]

  end

  scope module: :public do
    root 'homes#top'
    get 'map_search' => 'homes#map_search', as: 'map_search'


    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'

    resources :customers, only: [:show] do
      member do
        get :favorites
        get :reviews
      end
    end


    resources :restaurants, only: [ :show, :index] do
      resource :favorites, only: [:create, :destroy]
      resources :reviews, only: [:create,:destroy,:update]
    end

  end





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates:name,presence:true

  has_many :restaurants,dependent: :destroy

  scope :only_active, -> { where(is_active: true) }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_genre, only: [:show, :edit, :update]


  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: 'ジャンルの登録が完了しました。'
    else
      @genres = Genre.all
      render :index
    end
  end

  def update
    if @genre.update(genre_params)
      unless @genre.is_active
        @genre.restaurants.update_all(is_active: false)
      end
      redirect_to admin_genres_path, notice: 'ジャンルの更新が完了しました。'
    else
      render :edit
    end
  end


  private

  def genre_params
    params.require(:genre).permit(:name,:genre_id,:is_active)
  end

  def ensure_genre
    @genre = Genre.find(params[:id])
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_form.html.erb
<%= form_with model:genre, url: url do |f| %>
	<%= f.label :name, "ジャンル名:" %>
	<%= f.text_field :name %>
	<%= f.radio_button :is_active, true %>
	<%= f.label :is_active, "有効", value: true, class: "text-active" %>
	<%= f.radio_button :is_active, false %>
	<%= f.label :is_active, "無効", value: false, class: "text-invalid" %>
	<%= f.submit submit, class: "admin-btn" %>
<% end %>

app/views/admin/genres/edit.html.erb
<section class="container">
	<h2 class="section-ttl">ジャンル新規登録</h2>
  <%= render 'form', genre: @genre, url: admin_genre_path(@genre), submit: '更新' %>
</section>

app/views/admin/genres/index.html.erb
<div class="container">
  <h3>ジャンル一覧・追加</h3>
  <div class="row px-3 py-2">
    <p>新規登録 <p>
    <%= form_with model:@genre,url:admin_genres_path do |f| %>
    <%= f.text_field :name %>
    <%= f.submit '新規登録',class:"admin-btn" %>
    <% end %>
  </div>

  <div class="row mb-3">
    <div class="col-sm-7">
      <table class="table">
        <thead>
          <th>ジャンル</th>
          <th></th>
        </thead>
        <tbody>
         <% @genres.each do |genre| %>
          <tr>
            <td>
              <%= genre.name %>
            </td>
           <td>
             <%= link_to "編集する",edit_admin_genre_path(genre.id) %>
           </td>
          </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>