config/routes.rb
Rails.application.routes.draw do

   devise_for :customers,controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions',
    passwords: "public/passwords"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }

  namespace :admin do

    resources :customers, only: [:index, :show, :edit, :update]
    resources:restaurants,only:[:index,:new,:create,:show,:edit,:update,:destroy]
    resources:reviews,only:[:index,:edit,:update]
    resources :genres, only: [:index, :create, :edit, :update]

  end

  scope module: :public do
    root 'homes#top'
    get 'map_search' => 'homes#map_search', as: 'map_search'


    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'

    resources :customers, only: [:show] do
      member do
        get :favorites
        get :reviews
      end
    end


    resources :restaurants, only: [ :show, :index] do
      resource :favorites, only: [:create, :destroy]
      resources :reviews, only: [:create,:destroy,:update]
    end

  end





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  include Rails.application.routes.url_helpers

  has_one_attached:image
  has_many :favorites,dependent: :destroy
  has_many :reviews,dependent: :destroy
  belongs_to :genre

  validates:name,presence:true
  validates:business_time,presence:true
  validates:price,presence:true
  validates:telephone_number,presence:true
  validates:address,presence:true
  validates:is_active, inclusion: [true, false]

  scope :where_genre_active, -> { joins(:genre).where(genres: { is_active: true }) }

  scope :active_restaurant, -> { where(is_active: true) }


  geocoded_by :address
  after_validation :geocode

  acts_as_mappable default_units: :kms,
                   lat_column_name: :latitude,
                   lng_column_name: :longitude

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.png')
      image.attach(io: File.open(file_path), filename: 'no-image.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit:[width,height]).processed
  end

  def self.recommended
    recommends = []
    active_genres = Genre.only_active.includes(:restaurants)
    active_genres.each do |genre|
      restaurant = genre.restaurants.last
      recommends << restaurant if restaurant
    end
    recommends
  end

  def favorited_by?(customer)
    favorites.where(customer_id: customer).exists?
  end

  def image_url
    {record_id: image.record_id, url: image.attached? ? url_for(image) : nil}
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_restaurant, only: [:show, :edit, :update]

  def index
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      all_restaurans = @genre.restaurants
    else
      all_restaurans = Restaurant.includes(:genre)
    end
    @restaurants = Restaurant.all
    @all_restaurans_count = all_restaurans.count
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to admin_restaurant_path(@restaurant), notice: '店舗の登録が完了しました。'
    else
      flash[:alert] = '入力項目が不足しています'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params) ? (redirect_to admin_restaurant_path(@restaurant), notice: '店舗情報の更新が完了しました。') : (render :edit)
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name,:business_time,:price,:telephone_number,:address,:is_active,:image, :latitude, :longitude,:genre_id)
  end

  def ensure_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<div class="admin-page">
<%= form_with(model:restaurant, url: url) do |f| %>
	<div class="flex align-items-center justify-content-center">
		<div>
			<%= f.label :image, "画像" %>
			<div class="admin-image-form py-2">
				<%= image_tag (restaurant.image.attached? ? restaurant.image : 'no-image.png'), id: "img_prev", class: "admin_restaurant_image" %>
				<span class="btn btn-file btn-info"><%= f.file_field :image,  accept:'image/*' %></span>
			</div>
		</div>
		<table>
			<tbody>
				<tr>
					<td><%= f.label :name, "店舗名" %></td>
					<td><%= f.text_field :name %></td>
				</tr>
				<tr>
					<td><%= f.label :genre_id, "ジャンル" %></td>
					<td class="select_field"><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
				</tr>
				<tr>
					<td><%= f.label :business_time, "営業時間" %></td>
					<td><%= f.text_field :business_time, rows: 3 %></td>
				</tr>
				<tr>
					<td><%= f.label :price, "平均予算" %></td>
					<td><%= f.number_field :price %> 円〜</td>
				</tr>
				<tr>
					<td><%= f.label :telephone_number, "電話番号" %></td>
					<td><%= f.text_field :telephone_number %></td>
				</tr>
				<tr>
					<td><%= f.label :address, "住所" %></td>
					<td><%= f.text_field :address %></td>
				</tr>
				<tr>
					<td><%= f.label :sales_status, "表示ステータス" %></td>
					<td class="select_field">
						<%= f.radio_button :is_active, true %>
						<%= f.label :is_active, "有効", value: true, class: "text-active" %>
						<%= f.radio_button :is_active, false %>
						<%= f.label :is_active, "無効", value: false, class: "text-invalid" %>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="flex align-center pl5">
			<%= f.submit "登録", class: "admin-btn" %>
		</div>
	</div>
<% end %>
</div>

app/views/admin/restaurants/edit.html.erb
<section class="container">
	<h3><%= @restaurant.name %>の編集</h3>
  <%= render 'form', restaurant: @restaurant, url: admin_restaurant_path(@restaurant), submit: '更新' %>
</section>

app/views/admin/restaurants/index.html.erb
<div class="container">
	<h3>店舗一覧</h3>
	<div class="text-left h2">
			<%= link_to new_admin_restaurant_path do %>
				<i class="fas fa-plus-circle"></i>
			<% end %>
	</div>
	<table class="table table-sm">
		<thead>
			<tr>
				<th>店舗ID</th>
				<th>店舗名</th>
				<th>表示ステータス</th>
			</tr>
		</thead>
		<tbody>
			<% @restaurants.each do |restaurant| %>
				<tr>
					<td><%= restaurant.id %></td>
					<td><%= link_to restaurant.name, admin_restaurant_path(restaurant), class: "underline" %></td>
					<td>
						<% if restaurant.is_active? %>
							<span class="text-active">表示中</span>
						<% else %>
							<span class="text-invalid">表示停止中</span>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/restaurants/new.html.erb
<section class="container">
	<h3>店舗新規登録</h3>
  <%= render 'form', restaurant: @restaurant, url: admin_restaurants_path, submit: '登録' %>
</section>

app/views/admin/restaurants/show.html.erb
<section class="container">
	<h3>店舗詳細</h3>
	<div>
		<div class="admin-page">
			<%= image_tag @restaurant.get_image(200,200), id: "img_prev", class: "admin_item_image" %>
		</div>
	</div>
	<div class="restaurant-show">
		<dl>
			<dd>店舗名 : <%= @restaurant.name %></dd>
			<dd>ジャンル : <%= link_to @restaurant.genre.name, restaurants_path(genre_id: @restaurant.genre_id) %></dd>
			<dd>営業時間 : <%= @restaurant.business_time %></dd>
			<dd>平均予算 : <%= @restaurant.price%>円〜</dd>
			<dd>電話 : <%= @restaurant.telephone_number %></dd>
			<dd>住所 : <%= @restaurant.address %></dd>
			<dd>
				表示ステータス : 
					<% if @restaurant.is_active? %>
						<span class="text-active">表示中</span>
					<% else %>
						<span class="text-invalid">表示停止中</span>
					<% end %>
			</dd>
			<dd>マップ : </dd>
			<div id="map" style="width:300px; height:200px"></div>
		</dl>
	</div>
	<div class="admin-btn">
		<%= link_to "編集する", edit_admin_restaurant_path(@restaurant), class: "btn" %>
	</div>
	<!--地図表示-->
	<script>
    function initMap(){
    	let mapPosition = {lat: <%= @restaurant.latitude || 0 %> , lng: <%= @restaurant.longitude || 0 %> };
      let map = new google.maps.Map(document.getElementById('map'), {
      	zoom: 15,
      	center: mapPosition
      });

      let transitLayer = new google.maps.TransitLayer();
    	transitLayer.setMap(map);

    	let contentString = '<%= @restaurant.name %>';
 			let infowindow = new google.maps.InfoWindow({
      	content: contentString
    	});

      let marker = new google.maps.Marker({
    	  position: mapPosition,
      	map: map,
      	title: contentString
    	});

	    marker.addListener('click', function(){
  	    infowindow.open(map, marker);
    	});
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>

</section>