config/routes.rb
Rails.application.routes.draw do

   devise_for :customers,controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions',
    passwords: "public/passwords"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }

  namespace :admin do

    resources :customers, only: [:index, :show, :edit, :update]
    resources:restaurants,only:[:index,:new,:create,:show,:edit,:update,:destroy]
    resources:reviews,only:[:index,:edit,:update]
    resources :genres, only: [:index, :create, :edit, :update]

  end

  scope module: :public do
    root 'homes#top'
    get 'map_search' => 'homes#map_search', as: 'map_search'


    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'

    resources :customers, only: [:show] do
      member do
        get :favorites
        get :reviews
      end
    end


    resources :restaurants, only: [ :show, :index] do
      resource :favorites, only: [:create, :destroy]
      resources :reviews, only: [:create,:destroy,:update]
    end

  end





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h5>
      <%= I18n.t("errors.messages.not_sign_up",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h5>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EatingPickOut</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= include_gon %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/" data-turbolinks="false">
            <i class="fas fa-utensils"></i>  EatingPickOut
          </a>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expand="false" aria-label="Toggle navigation">
            <sppan class="navbar-toggler-icon"></sppan>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="nav navbar-nav">
              <% if customer_signed_in? %>
                <li class="nav-item">
                  <%= link_to "マップから探す", map_search_path,class:'navlink' %>
                </li>
                <li class="nav-item">
                  <%= link_to "飲食店一覧", restaurants_path,class:'navlink' %>
                </li>
                <li class="nav-item">
                  <%= link_to "マイページ", customer_path(current_customer.id),class:'navlink' %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class:'navlink' %>
                </li>
              <% else %>
                <% if admin_signed_in? %>
                  <li class="nav-item">
                    <%= link_to "店舗一覧",admin_restaurants_path,class:'navlink' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ジャンル一覧", admin_genres_path,class:'navlink' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "会員一覧", admin_customers_path,class:'navlink' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "レビュー一覧", admin_reviews_path,class:'navlink' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class:'navlink' %>
                  </li>
                <% else %>
                <li class="nav-item">
                  <%= link_to "マップから探す", map_search_path,class:'navlink' %>
                </li>
                  <li class="nav-item">
                    <%= link_to "飲食店一覧", restaurants_path,class:'navlink' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "新規登録", new_customer_registration_path,class:'navlink' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログイン", new_customer_session_path,class:'navlink' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'ゲストログイン（閲覧用）', customers_guest_sign_in_path, method: :post ,class:'navlink' %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <h7>※現在登録されている飲食店は架空のものになります※</h7>
      <%= yield %>
    </main>
    <footer>
      </br></br>
    </footer>
  </body>
</html>